server:
  port: 8009 #local environment setup
  servlet:
    context-path: /
spring:
  application:
    name: login-api
  datasource:
    # local database
    url: jdbc:mysql://localhost:3306/achievers
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 10
    initial-size: 5
    max-idle: 5
    min-idle: 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    time-between-eviction-runs-millis: 5000
    min-evictable-idle-time-millis: 60000


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#used trail account
twilio:
  account-sid: AC8838db13d697629c0bb7470fd4410671
  auth-token: 6b234658f69c43e7c1bc2b5fb13d25c5
  twilio-phone-number: +14793415852
  message: 'You know the rituals.. Use OTP: otp to login'
jwt:
  # generated USING SSL
  secret: x6flVGdmTVBxKMWlHQJ+8cTUjBldDMN2hm1lNer/GBA=

